### ISSUE TITLE
Error TypeError: listeners[i] is not a function with example code

### ISSUE THREAD

**Issue by carloslfu** [dominictarr/epidemic-broadcast-trees#4]
Hello @dominictarr, when I run the example code a `TypeError: listeners[i] is not a function` error occurs. See code running here: [https://runkit.com/carloslfu/58f98490b7c4ff00127fe01c](https://runkit.com/carloslfu/58f98490b7c4ff00127fe01c).

Note: Thanks for sharing all these awesome projects, all those are exciting :smiley: .

**Comment by dominictarr** [comment]
oh, sorry - probably the readme code is not 100% up to date, but look at the code in example.js - it's actually used in the tests, so I am sure it is good

**Comment by dominictarr** [comment]
oh, sorry - probably the readme code is not 100% up to date, but look at the code in example.js - it's actually used in the tests, so I am sure it is good

**Comment by carloslfu** [comment]
Thanks @dominictarr
